version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  static_site_generator:
    docker:
    - image: cimg/python:3.10.6
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - run: 
        name: Site Generator
        command: python3 ssg.py --source content --dest test
    - run:
        name: Install Netlify CLI
        command: npm install netlify-cli
    - run:
        name: Deploy to Netlify
        command: netlify deploy --auth $NETLIFY_AUTH_TOKEN --dir ~/test --site gregarious-brigadeiros

workflows:
  workflow:
    jobs:
      - static_site_generator:
          context: netlify
