version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  static_site_generator:
    docker:
    - image: cimg/python:3.10.6
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - run: 
        name: Site Generator
        command: python3 ssg.py --source content --dest test
    - run:
        name: List new files
        command: cd ~/test && ls -la

workflows:
  workflow:
    jobs:
    - static_site_generator
