version: 2.1

# setup: true

orbs:
  python: circleci/python@2.0.3
  path-filtering: circleci/path-filtering@0.1.1
 

jobs:
  static_site_generator:
    docker:
    - image: cimg/python:3.10.6-node
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - run: 
        name: Site Generator
        command: python3 ssg.py --source content --dest test
    - persist_to_workspace:
        root: ~/
        paths: 
          - project/test
  deploy_site:
        docker:
    - image: cimg/python:3.10.6-node
    steps:
      - attach_workspace:
          at: ~/project/
      - run:
          name: Install Netlify CLI
          command: sudo npm install netlify-cli -g
      - run:
          name: Deploy to Netlify
          command: netlify deploy --auth $NETLIFY_AUTH_TOKEN --dir ~/project/test --site gregarious-brigadeiros

workflows:
#   always-run:
#     jobs:
#       # the path-filtering/filter job determines which pipeline
#       # parameters to update.
#       - path-filtering/filter:
#           name: check-updated-files
#           # 3-column, whitespace-delimited mapping. One mapping per
#           # line:
#           # <regex path-to-test> <parameter-to-set> <value-of-pipeline-parameter>
#           mapping: |
#             service1/.* run-build-service-1-job true
#             service2/.* run-build-service-2-job true
#           base-revision: main
#           # this is the path of the configuration we should trigger once
#           # path filtering and pipeline parameter value updates are
#           # complete. In this case, we are using the parent dynamic
#           # configuration itself.
#           config-path: .circleci/continue_config.yml
  workflow:
    jobs:
    - static_site_generator
    - deploy_site:
        context: netlify
