version: 2.1

orbs:
  python: circleci/python@2.0.3
  netlify: assurance-maladie-digital/netlify@1.1.0

jobs:
  static_site_generator:
    docker:
    - image: cimg/python:3.10.6-node
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - run: 
        name: Site Generator
        command: python3 ssg.py --source content --dest test
    - netlify/deploy:
        folder: ~/test

workflows:
  workflow:
    jobs:
    - static_site_generator:
        context: netlify
