version: 2.1
jobs:
  static_site_generator:
    docker:
    - image: cimg/python:3.10.6
    steps:
    - run: python3 ssg.py --source content --dest test
workflows:
  workflow:
    jobs:
    - static_site_generator
