version: 2.1

executors:
  base:
    docker:
      - image: cimg/python:3.10.6-node

parameters:
  test-one:
    type: boolean
    default: false
    
jobs:
  deploy_site:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/test
      - run:
          name: Install Netlify CLI
          command: sudo npm install netlify-cli -g
      - run:
          name: Deploy to Netlify
          command: netlify deploy --auth $NETLIFY_AUTH_TOKEN --dir ~/project/test --site gregarious-brigadeiros
              
workflows:
  deploy_to_netlify:
    when: << pipeline.parameters.test-one >>
    jobs:
      - deploy_site:
          context: netlify
